# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Castaner Extension"
client_id = "d6aa2feb73f46a7ea05d4f24b5ab8a1e"
application_url = "https://prospective-mines-crucial-int.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkout_branding_settings,write_checkout_branding_settings,write_pixels,read_shipping,write_shipping,read_customer_events,read_pixels,read_content,write_content,write_products,read_products,read_delivery_customizations,write_delivery_customizations,read_discounts,write_discounts,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://prospective-mines-crucial-int.trycloudflare.com/auth/callback",
  "https://prospective-mines-crucial-int.trycloudflare.com/auth/shopify/callback",
  "https://prospective-mines-crucial-int.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ohd-mcc-development.myshopify.com"
