# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d6aa2feb73f46a7ea05d4f24b5ab8a1e"
name = "Castaner Extension"
application_url = "https://concept-places-wage-galaxy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ohd-mcc-development.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customer_events,read_customers,read_delivery_customizations,read_discounts,read_merchant_managed_fulfillment_orders,read_orders,read_pixels,read_products,read_shipping,write_cart_transforms,write_checkout_branding_settings,write_content,write_customers,write_delivery_customizations,write_discounts,write_pixels,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://concept-places-wage-galaxy.trycloudflare.com/auth/callback",
  "https://concept-places-wage-galaxy.trycloudflare.com/auth/shopify/callback",
  "https://concept-places-wage-galaxy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
